Fix test decision in TestNetFilterCounters test
/proc/sys/net/netfilter/nf_conntrack_count is not path exists in all of
the test environment.
If this path does not exist, this will change to displays a message that path
does not exist, and then finish the test.

------
=== RUN   TestNetFilterCounters
--- FAIL: TestNetFilterCounters (0.00s)
	net_test.go:207: could not get NetConnections: open
		/proc/sys/net/netfilter/nf_conntrack_count: no such file or
		directory
FAIL
FAIL    github.com/shirou/gopsutil/net  0.028s
=== RUN   Test_SendSignal
------

Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>